[package]
name = "ukendio/jecs"
version = "0.1.0-rc.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["default.project.json", "lib", "wally.toml", "README.md"]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"