name: Lint

on: [push, pull_request, workflow_dispatch]

jobs:
  style:
    name: Run Stylua
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Run Stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest # NOTE: we recommend pinning to a specific version in case of formatting changes
          # CLI arguments
          args: --check ./src

  analyze:
    name: Run Luau Analyze
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        
      - name: Install Luau
        uses: encodedvenom/install-luau@v2.1
        
      - name: Analyze
        run: |
          luau-analyze src
